project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "coding-snippet"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Data wrangling"
        contents:
          - section: "Data types"
            contents:
              - data-wrangling/dates.qmd
          - section: "Control flow"
            contents:
              - data-wrangling/choices.qmd
              - data-wrangling/loops.qmd
          - section: "Data frames"
            contents:
              - data-wrangling/reading_data.qmd
              - data-wrangling/filtering.qmd
              - data-wrangling/joins.qmd
              - data-wrangling/window_functions.qmd
              - data-wrangling/altering.qmd
              - data-wrangling/exporting_data.qmd
          - data-wrangling/faking.qmd
      - section: "Coding styles"
        contents:
          - coding-styles/functions.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    page-layout: full
    toc: true
