project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "coding-snippet"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    search: true
    contents: auto
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    page-layout: full
    toc: true
