project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "coding-snippet"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Data wrangling"
        contents:
          - section: "Control flow"
            contents:
              - data-wrangling/choices.qmd
          - section: "Data frames"
            contents:
              - data-wrangling/filtering.qmd
          - data-wrangling/faking.qmd
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    page-layout: full
    toc: true
