project:
  type: website
  output-dir: docs
  
website:
  title: "coding-snippet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Control Flow"
        contents:
          - href: control_flow_choices.qmd
            text: Choices
          - href: control_flow_loops.qmd
            text: Loops
      - section: "Data Frames"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    page-layout: full
    toc: true



