---
title: "Heat maps & Mosaic"
---
```{r, setup, include=FALSE}
source("setup.R")
```

```{python}
#| echo: false
#| message: false
orders = r.orders
products = r.products
customers = r.customers
suppliers = r.suppliers
ChickWeight = r.ChickWeight
babynames = r.babynames
```

## Heat maps

:::{.panel-tabset}

## R

```{r, message=FALSE}
library(tidyverse)
library(dplyr)
#library(ggplot2)
babynames %>% 
  filter(
    year %in% 2014:2017,
    n > 1000
    ) %>%
  group_by(name, sex) %>% 
  summarize(mean = mean(n)) %>% 
  ungroup() %>% 
  group_by(name) %>% 
  mutate(
    proz = mean/sum(mean)*100,
    diff = abs(proz-50)
  ) %>% 
  ungroup() %>%
  arrange(diff) %>% 
  slice_head(n=8) %>% 
  ggplot(
    aes(
      x = name,
      y = sex,
      fill = proz
    )
  ) +
  geom_tile() +
  labs(
    title = "Babynames for both boyz and girls",
    subtitle = "Powered by the babynames package",
    x = "Name",
    y = "Gender",
    fill = "%"
  ) +
  theme_minimal()

  
```
:::

## Mosaic plots

:::{.panel-tabset}

## R

```{r, message=FALSE}

# library(ggplot2)
# library(ggmosaic)

data(iris)

iris %>% 
  mutate(
    Sepal.Length = case_when(
      Sepal.Length <5 ~"<5",
      Sepal.Length >=5 & Sepal.Length < 6  ~"5-6",
      Sepal.Length >=6 ~">6"
    )
  ) %>% 
  ggplot() +
  ggmosaic::geom_mosaic(aes(x = product(Species, Sepal.Length), fill = Species)) +
  labs(title = "Proportion of Species by Sepal.Length",
       subtitle = "Mosaic Plot using Iris Dataset")

  
```

:::
