---
title: "Line plot"
---
```{r, setup, include=FALSE}
source("setup.R")
```

```{python}
#| echo: false
#| message: false
orders = r.orders
products = r.products
customers = r.customers
suppliers = r.suppliers
ChickWeight = r.ChickWeight
babynames = r.babynames
```

## Perfect for 2 categorial + 1 numerical variables

::: {.panel-tabset}

## R

```{r, message=FALSE}

#library(ggplot2)
lineplot <- babynames %>% 
  filter(name %in% c("Mona", "Anna", "Lisa"), sex == "F") %>% 
  ggplot(
    aes(
      x = year,
      y = n,
      color = name
    )
  ) +
  geom_line() +
  labs(
    title = "Amount of named Babies per year in US",
    subtitle = "Selection of Anna, Mona and Lisa",
    x = "Year",
    y = "Number of Babies",
    color = "Name"  #Legend title
  ) +
  scale_color_manual(
    values = c("Anna" = "#d94a62", "Lisa" = "#a4eb8f", "Mona"="darkblue"),
    breaks = c("Mona", "Lisa","Anna") # Order in the Legend
  ) +
  theme_minimal()

print(lineplot)
  
    
```


```{r, message=FALSE}

library(ggplot2)
library(lubridate) # For handling dates

# Create a data frame with the start and end dates of the last 10 presidents
presidents_data <- data.frame(
  President = c(
    "Ronald Reagan", "George H. W. Bush", "Bill Clinton", "George W. Bush",
    "Barack Obama", "Donald Trump", "Joe Biden"
  ),
  Start_Date = as.Date(c(
    "1981-01-20", "1989-01-20", "1993-01-20", "2001-01-20",
    "2009-01-20", "2017-01-20", "2021-01-20"
  )),
  End_Date = as.Date(c(
    "1989-01-20", "1993-01-20", "2001-01-20", "2009-01-20",
    "2017-01-20", "2021-01-20", "2025-01-20"
  ))
) %>% mutate(
  President = factor(President) %>% fct_reorder(Start_Date, .fun="min")
) 

# Create a ggplot2 plot
ggplot(presidents_data, aes(y = President, xmin = Start_Date, xmax = End_Date, color = President)) +
  geom_linerange() +
  labs(title = "Term Duration of the Last 10 U.S. Presidents",
       x = "President", y = "Term Duration") +
  scale_x_date(
    date_labels = "%Y",
    date_breaks = "5 years",
    ) +
  theme_minimal() +
  theme(
    legend.position = "none"
  )

```

:::