---
title: "Strings & Factors"
---
```{r, setup, include=FALSE}
source("setup.R")
```

```{python}
#| echo: false
#| message: false
orders = r.orders
products = r.products
customers = r.customers
suppliers = r.suppliers
```

## Converting character data type to factors (= ordered strings with levels)

::: {.panel-tabset}
## R

### Ordering by character (default is alphabetically)
```{r}
library(tibble)

# Create a tibble with the star ratings
df_rating <- tibble(stars_chr = c("Five Stars","One Star", "Two Stars", "Three Stars", "Four Stars", "Five Stars", "Two Stars")) %>%
  mutate(
    stars_fct = factor(stars_chr, levels=c("One Star", "Two Stars", "Three Stars", "Four Stars", "Five Stars"))
  )
# df_rating ordered by character
df_rating %>% arrange(stars_chr)

```

### Ordering by factors (levels)

```{r}

# df_rating ordered by factors
df_rating %>% arrange(stars_fct)

```

### Ordering by factors (levels in order)

```{r}


df_reordered <- df_rating %>% mutate(
  num = case_when(
    stars_chr == "One Star" ~ 1,
    stars_chr == "Two Stars" ~ 2,
    stars_chr == "Three Stars" ~ 3,
    stars_chr == "Four Stars" ~ 4,
    stars_chr == "Five Stars" ~ 5
  )
) %>% 
  arrange(num) %>% 
  mutate(
    # another way to order factors if they are already in order:
    stars_chr = fct_inorder(stars_chr) 
  )
df_reordered

```


### Reversing factor order

```{r}

df_reordered_rev  <- df_reordered %>% 
  mutate(
    stars_fct = fct_rev(stars_fct)
  ) %>% 
  arrange(stars_fct)

df_reordered_rev

```

:::
